Testing in Python
rharris-nitro/pythonExercise1 pull request #6
Opened 2024-02-20 10:18 UTC by rharris-nitro

Opens up python testing and uses docker to sort between the main app and the testing side.
Also, helps understands Docker way more.

2024-02-21 11:02 UTC, rlasskiy commented on docs/how-to-git.md
> +    participant U as Working Directory (Untracked)
`participant directory as Working Directory (Untracked)`

it will be easy to read the diagram if you use the proper names

2024-02-21 11:04 UTC, rlasskiy commented on docs/how-to-git.md
> +    O-->>U: git clone (GitHub URL)
`O-->>U: git fetch (remote repo)`

2024-02-21 11:04 UTC, rlasskiy commented on docs/how-to-git.md
> +    O-->>H: git clone (GitHub URL)
O-->>H: git fetch (remote repo)

2024-02-21 16:44 UTC, rlasskiy commented on Dockerfile
> +FROM base AS test
`FROM main as test`

2024-02-21 16:44 UTC, rlasskiy commented on Dockerfile
> +    COPY ./app/main.py .
COPY app/ app/

2024-02-21 16:49 UTC, rlasskiy commented
delete 
- app/__pycache__/
- tests/__pycache__/

2024-02-21 16:59 UTC, rlasskiy requested changes

2024-02-21 16:59 UTC, rlasskiy commented on Dockerfile
> +    COPY app/ app/
remove `  COPY app/ app/`

2024-02-21 16:59 UTC, rlasskiy commented on app/main.py
> +class Main:
class Data

2024-02-21 16:59 UTC, rlasskiy commented on app/main.py
> +        # self.integer_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
please not store commented code in Githib

2024-02-21 17:06 UTC, rlasskiy commented
remove `.DS_Store`

2024-02-22 11:48 UTC, rharris-nitro commented on Dockerfile
> +    COPY app/ app/
moved to main image

2024-02-22 11:49 UTC, rharris-nitro commented on app/main.py
> +class Main:
changed Main to Data

2024-02-23 11:53 UTC, rlasskiy approved these changes

2024-02-23 11:53 UTC, merged